import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { buildDescriptor } from './build-descriptor'
import { detectVerbCollisions, emit } from './emit'
import type { ApiDescriptor } from '@haddowg/json-api-client'
import type { OpenApiDocument } from './openapi'

function loadFixture(name: string): OpenApiDocument {
  const path = fileURLToPath(new URL(`../test/fixtures/${name}`, import.meta.url))
  return JSON.parse(readFileSync(path, 'utf8')) as OpenApiDocument
}

const doc = loadFixture('music-catalog.openapi.json')
const descriptor = buildDescriptor(doc)
const source = emit(doc, descriptor)

describe('emit (music-catalog default server)', () => {
  it('writes a do-not-edit header and the runtime import', () => {
    expect(source).toContain('AUTO-GENERATED by @haddowg/json-api-codegen')
    expect(source).toContain("from '@haddowg/json-api-client'")
    expect(source).toContain('createClient as createClientRuntime')
  })

  it('emits an enum union alias only for a referenced enum', () => {
    expect(source).toContain('export type AlbumStatus = "upcoming" | "released" | "withdrawn"')
  })

  it('emits a precise AlbumsAttributes interface', () => {
    expect(source).toContain('export interface AlbumsAttributes {')
    expect(source).toContain('title: string')
    expect(source).toContain('averageRating: number | null')
    expect(source).toContain('artwork: string | null')
    expect(source).toContain('releasedAt: string')
    expect(source).toContain('explicit: boolean')
    expect(source).toContain('status: AlbumStatus')
    expect(source).toContain('availableFrom: string | null')
    // Nested object attribute with its own members (source order preserved), nullable.
    expect(source).toContain('releaseInfo: { label?: string; catalogueNumber?: string } | null')
  })

  it('types an array attribute (tracks.genres)', () => {
    expect(source).toContain('export interface TracksAttributes {')
    expect(source).toContain('genres: unknown[]')
  })

  it('emits an empty interface for an attribute-less type (users)', () => {
    expect(source).toContain('export interface UsersAttributes {}')
  })

  it('emits the resourceMap as const satisfies ApiDescriptor', () => {
    expect(source).toContain('export const resourceMap = {')
    expect(source).toContain('as const satisfies ApiDescriptor')
    expect(source).toContain('export type ResourceMap = typeof resourceMap')
  })

  it('encodes pivot and polymorphic relations in the resourceMap', () => {
    // playlists.orderedTracks is a pivot to-many.
    expect(source).toMatch(/orderedTracks: \{[\s\S]*?pivot: true/)
    // libraries.items is a polymorphic to-many.
    expect(source).toMatch(/items: \{[\s\S]*?types: \[\s*"tracks",\s*"albums",\s*"artists"\s*\]/)
  })

  it('quotes a hyphenated wire-type key', () => {
    expect(source).toContain('"public-profiles": {')
  })

  it('emits the descriptor-bound createClient factory', () => {
    expect(source).toContain('export const createClient = (options: ClientOptions) =>')
    expect(source).toContain('createClientRuntime(resourceMap, options)')
  })

  it('matches the committed, type-checked snapshot', async () => {
    await expect(source).toMatchFileSnapshot('../test/generated/music-catalog.client.gen.ts')
  })
})

describe('emit (music-catalog admin server)', () => {
  it('generates cleanly from the admin document', () => {
    const adminDoc = loadFixture('music-catalog-admin.openapi.json')
    const adminSource = emit(adminDoc, buildDescriptor(adminDoc))
    expect(adminSource).toContain('export const resourceMap = {')
    expect(adminSource).toContain('export interface AlbumsAttributes {')
    // The admin server's users type carries real attributes (unlike the default server).
    expect(adminSource).toContain('export interface UsersAttributes {')
    expect(adminSource).toContain('email: string')
    expect(adminSource).toContain('preferences: Record<string, unknown>')
  })
})

describe('detectVerbCollisions', () => {
  it('finds no collisions in the real fixture', () => {
    expect(detectVerbCollisions(descriptor)).toEqual([])
  })

  it('reports a relation named like a reserved verb', () => {
    const synthetic: ApiDescriptor = {
      widgets: {
        attributes: {},
        relations: {
          update: { cardinality: 'one', types: ['gadgets'], pivot: false },
          owner: { cardinality: 'one', types: ['users'], pivot: false },
        },
        paths: {},
        paginator: 'none',
        clientId: 'forbidden',
      },
    }
    expect(detectVerbCollisions(synthetic)).toEqual([{ type: 'widgets', relation: 'update' }])
  })
})
