import { hashJson } from './provenance'
import type { SchemaBundle } from './reader'

/**
 * Emit the per-type JSON Schema map as a standalone generated artifact:
 *
 * ```ts
 * export const schemas = { <type>: { …json schema… }, … } as const
 * ```
 *
 * The values are the raw, self-contained resource-object JSON Schema documents the bundle
 * serves at `GET /schemas.json` — suitable to hand straight to a validation engine via the
 * opt-in `validate?` seam (ADR 0004). This is a separate file from the client so the main
 * descriptor/client output is unaffected when `--schemas` is absent.
 *
 * The schemas are emitted as JSON (deterministic, key order preserved) so the artifact is
 * stable to diff; `as const` keeps the literal shapes narrow.
 */
export function emitSchemas(bundle: SchemaBundle): string {
  return `${[header(bundle), body(bundle)].join('\n\n')}\n`
}

function header(bundle: SchemaBundle): string {
  return [
    '/**',
    ' * AUTO-GENERATED by @haddowg/json-api-codegen — do not edit by hand.',
    ' * Per-type JSON Schemas for the opt-in validation seam; regenerate from the source bundle.',
    ' *',
    ` * Schema hash: ${hashJson(bundle)}`,
    ' */',
  ].join('\n')
}

function body(bundle: SchemaBundle): string {
  // `JSON.stringify` with two-space indent gives deterministic, diff-friendly output while
  // preserving the bundle's key order. The raw schema objects are valid TS object literals.
  const json = JSON.stringify(bundle, null, 2)
  return `export const schemas = ${json} as const`
}
