import {
  type ApiDescriptor,
  HANDLE_RESERVED,
  type ResourceDescriptor,
} from '@haddowg/json-api-client'
import type { OpenApiDocument, SchemaObject, SchemaOrBool } from './openapi'

const REF_PREFIX = '#/components/schemas/'

/** A relation name that will later collide with a fluent-surface verb. */
export interface VerbCollision {
  type: string
  relation: string
}

/**
 * The reserved relation names: the members the read handle actually shadows (kept in sync
 * via the runtime's {@link HANDLE_RESERVED}) plus the future Phase-3 write verbs. A relation
 * named like any of these must route through `.rel(name)`, so the codegen warns at build time.
 * (`type`/`id` from {@link HANDLE_RESERVED} can never be JSON:API relation names.)
 */
const RESERVED_VERBS = new Set<string>([
  ...HANDLE_RESERVED,
  'update',
  'delete',
  'create',
  'list',
  'actions',
])

/**
 * Find relations whose name shadows a reserved fluent-surface member (a handle accessor or a
 * future write verb). Such relations are routed via `.rel(name)`; the codegen warns at build time.
 */
export function detectVerbCollisions(descriptor: ApiDescriptor): VerbCollision[] {
  const collisions: VerbCollision[] = []
  for (const type of Object.keys(descriptor)) {
    for (const relation of Object.keys(descriptor[type]!.relations)) {
      if (RESERVED_VERBS.has(relation)) {
        collisions.push({ type, relation })
      }
    }
  }
  return collisions
}

function refName(ref: string): string | undefined {
  return ref.startsWith(REF_PREFIX) ? ref.slice(REF_PREFIX.length) : undefined
}

function isSchema(value: SchemaOrBool | undefined): value is SchemaObject {
  return typeof value === 'object' && value !== null
}

/** PascalCase a JSON:API wire type for use in a TS identifier (e.g. `public-profiles` -> `PublicProfiles`). */
function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

/** Emit a JSON-string literal (used for keys that aren't bare identifiers and enum members). */
function quote(value: string): string {
  return JSON.stringify(value)
}

/** True when a string is a safe bare object-key identifier. */
function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)
}

function objectKey(value: string): string {
  return isIdentifier(value) ? value : quote(value)
}

/**
 * Render a description as a JSDoc comment at the given indent — single-line when it fits,
 * a block otherwise. Returns `undefined` for empty text. Neutralises any `*\/` so a
 * description can never terminate the comment early.
 */
function jsDoc(text: string | undefined, indent: string): string | undefined {
  const trimmed = text?.trim()
  if (!trimmed) {
    return undefined
  }
  const lines = trimmed.replace(/\*\//g, '* /').split('\n')
  if (lines.length === 1) {
    return `${indent}/** ${lines[0]} */`
  }
  return [
    `${indent}/**`,
    ...lines.map((line) => `${indent} * ${line}`.trimEnd()),
    `${indent} */`,
  ].join('\n')
}

export class Emitter {
  private readonly schemas: Record<string, SchemaObject>
  /** Wire type -> the schema `Base` (the `<Base>Resource` name minus `Resource`). */
  private readonly baseByType: Map<string, string>
  /** Enum component names referenced by an attribute, in first-seen order. */
  private readonly usedEnums = new Map<string, SchemaObject>()

  constructor(
    private readonly doc: OpenApiDocument,
    private readonly descriptor: ApiDescriptor,
  ) {
    this.schemas = doc.components?.schemas ?? {}
    this.baseByType = this.indexBases()
  }

  /** Map each declared wire type back to the `Base` of its resource schema. */
  private indexBases(): Map<string, string> {
    const out = new Map<string, string>()
    for (const [name, schema] of Object.entries(this.schemas)) {
      if (!name.endsWith('Resource') || name.endsWith('ResourceIdentifier')) {
        continue
      }
      const typeProp = schema.properties?.['type']
      if (isSchema(typeProp) && typeof typeProp.const === 'string') {
        out.set(typeProp.const, name.slice(0, -'Resource'.length))
      }
    }
    return out
  }

  emit(): string {
    // Resolve enums first so the alias block (which depends on `usedEnums`) is populated.
    const interfaces = Object.keys(this.descriptor).map((type) => this.attributeInterface(type))
    const enums = this.enumAliases()

    const parts = [
      this.header(),
      this.imports(),
      ...(enums ? [enums] : []),
      ...interfaces,
      this.attributesMap(),
      this.resourceMap(),
      'export type ResourceMap = typeof resourceMap',
      this.boundFactory(),
    ]
    return `${parts.join('\n\n')}\n`
  }

  private header(): string {
    return [
      '/**',
      ' * AUTO-GENERATED by @haddowg/json-api-codegen — do not edit by hand.',
      ' * Regenerate from the source OpenAPI document instead.',
      ' */',
    ].join('\n')
  }

  private imports(): string {
    return [
      'import {',
      '  type ApiDescriptor,',
      '  type ClientOptions,',
      '  createClient as createClientRuntime,',
      "} from '@haddowg/json-api-client'",
    ].join('\n')
  }

  /** Per-type attribute interface, e.g. `export interface AlbumsAttributes { ... }`. */
  private attributeInterface(type: string): string {
    const name = `${pascalCase(type)}Attributes`
    const base = this.baseByType.get(type)
    const props = base ? this.schemas[`${base}Attributes`]?.properties : undefined
    const descriptorAttrs = this.descriptor[type]!.attributes

    const lines: string[] = []
    // Drive field order off the (sorted) descriptor so output stays deterministic.
    for (const field of Object.keys(descriptorAttrs)) {
      const schema = props?.[field]
      const tsType = isSchema(schema) ? this.tsType(schema) : 'unknown'
      const doc = isSchema(schema) ? jsDoc(schema.description, '  ') : undefined
      if (doc) {
        lines.push(doc)
      }
      lines.push(`  ${objectKey(field)}: ${tsType}`)
    }

    if (lines.length === 0) {
      return `export interface ${name} {}`
    }
    return `export interface ${name} {\n${lines.join('\n')}\n}`
  }

  /** Map a JSON Schema attribute node to a precise TypeScript type. */
  private tsType(schema: SchemaObject): string {
    // An enum reference -> the emitted union alias.
    if (typeof schema.$ref === 'string') {
      const target = refName(schema.$ref)
      const resolved = target ? this.schemas[target] : undefined
      if (target && resolved && Array.isArray(resolved.enum)) {
        this.usedEnums.set(target, resolved)
        return target
      }
      return 'unknown'
    }

    const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : []
    const nullable = types.includes('null')
    const base = this.baseTsType(
      schema,
      types.filter((t) => t !== 'null'),
    )
    return nullable ? `${base} | null` : base
  }

  /** The non-nullable TS type for the declared JSON type(s). */
  private baseTsType(schema: SchemaObject, types: readonly string[]): string {
    // An inline enum (string literals without a $ref).
    if (Array.isArray(schema.enum) && schema.enum.length > 0) {
      return schema.enum.map((value) => quote(String(value))).join(' | ')
    }
    if (types.length === 0) {
      return 'unknown'
    }
    const mapped = types.map((t) => this.scalarOrComposite(schema, t))
    // De-dupe while preserving order.
    return [...new Set(mapped)].join(' | ')
  }

  private scalarOrComposite(schema: SchemaObject, type: string): string {
    switch (type) {
      case 'string': {
        return 'string'
      }
      case 'number':
      case 'integer': {
        return 'number'
      }
      case 'boolean': {
        return 'boolean'
      }
      case 'object': {
        return this.objectType(schema)
      }
      case 'array': {
        return this.arrayType(schema)
      }
      default: {
        return 'unknown'
      }
    }
  }

  /** A nested object type from its `properties` (falls back to an index signature). */
  private objectType(schema: SchemaObject): string {
    const props = schema.properties
    if (props === undefined) {
      return 'Record<string, unknown>'
    }
    const required = new Set(schema.required ?? [])
    const members: string[] = []
    for (const [name, prop] of Object.entries(props)) {
      if (!isSchema(prop)) {
        continue
      }
      const optional = required.has(name) ? '' : '?'
      members.push(`${objectKey(name)}${optional}: ${this.tsType(prop)}`)
    }
    if (members.length === 0) {
      return 'Record<string, unknown>'
    }
    return `{ ${members.join('; ')} }`
  }

  private arrayType(schema: SchemaObject): string {
    const items = schema.items
    const element = isSchema(items) ? this.tsType(items) : 'unknown'
    // Wrap unions so `(A | B)[]` reads correctly.
    return /[|&]/.test(element) ? `(${element})[]` : `${element}[]`
  }

  /** Union aliases for every enum component an attribute referenced, sorted by name. */
  private enumAliases(): string | undefined {
    if (this.usedEnums.size === 0) {
      return undefined
    }
    // oxlint-disable-next-line no-array-sort -- sorting a freshly-created key array
    const names = [...this.usedEnums.keys()].sort()
    return names
      .map((name) => {
        const schema = this.usedEnums.get(name)!
        const values = schema.enum ?? []
        const union = values.map((value) => quote(String(value))).join(' | ')
        const alias = `export type ${name} = ${union}`
        const doc = jsDoc(this.enumDoc(schema), '')
        return doc ? `${doc}\n${alias}` : alias
      })
      .join('\n\n')
  }

  /**
   * Documentation for an enum alias: a per-value list built from `x-enum-descriptions`
   * (the richest hover DX, since a union alias can't carry per-member JSDoc), falling
   * back to the component's own `description`.
   */
  private enumDoc(schema: SchemaObject): string | undefined {
    const values = schema.enum ?? []
    const descriptions = schema['x-enum-descriptions']
    if (Array.isArray(descriptions) && descriptions.length === values.length && values.length > 0) {
      return values
        .map((value, i) => `- \`${String(value)}\` — ${String(descriptions[i])}`)
        .join('\n')
    }
    return schema.description
  }

  /**
   * Emit the `Attributes` interface mapping each wire type to its per-type attribute
   * interface. The runtime descriptor only carries coarse format hints; this is how the
   * precise per-type attribute types reach the bound client (passed as the second type
   * argument to the runtime factory).
   */
  private attributesMap(): string {
    const lines = Object.keys(this.descriptor).map(
      (type) => `  ${objectKey(type)}: ${pascalCase(type)}Attributes`,
    )
    return `export interface Attributes {\n${lines.join('\n')}\n}`
  }

  /** Emit the descriptor as a literal `as const satisfies ApiDescriptor`. */
  private resourceMap(): string {
    const body = this.literal(this.descriptor as Record<string, unknown>, 0)
    return `export const resourceMap = ${body} as const satisfies ApiDescriptor`
  }

  /** Render a JSON-serialisable descriptor value as deterministic TS object-literal source. */
  private literal(value: unknown, depth: number): string {
    const indent = '  '.repeat(depth)
    const inner = '  '.repeat(depth + 1)

    if (Array.isArray(value)) {
      if (value.length === 0) {
        return '[]'
      }
      const items = value.map((item) => `${inner}${this.literal(item, depth + 1)}`)
      return `[\n${items.join(',\n')}\n${indent}]`
    }

    if (value !== null && typeof value === 'object') {
      const entries = Object.entries(value as Record<string, unknown>)
      if (entries.length === 0) {
        return '{}'
      }
      const lines = entries.map(
        ([key, v]) => `${inner}${objectKey(key)}: ${this.literal(v, depth + 1)}`,
      )
      return `{\n${lines.join(',\n')}\n${indent}}`
    }

    return JSON.stringify(value)
  }

  private boundFactory(): string {
    return [
      '/** Descriptor-bound client factory; wraps the generic runtime with this API’s `resourceMap`. */',
      'export const createClient = (options: ClientOptions) =>',
      '  createClientRuntime<typeof resourceMap, Attributes>(resourceMap, options)',
    ].join('\n')
  }
}

/** Generate the full source of the client module for a document + its built descriptor. */
export function emit(doc: OpenApiDocument, descriptor: ApiDescriptor): string {
  return new Emitter(doc, descriptor).emit()
}

/** Re-export so callers can reference the resource descriptor shape if needed. */
export type { ResourceDescriptor }
