import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { emitSchemas } from './emit-schemas'
import type { SchemaBundle } from './reader'

function loadBundle(name: string): SchemaBundle {
  const path = fileURLToPath(new URL(`../test/fixtures/${name}`, import.meta.url))
  return JSON.parse(readFileSync(path, 'utf8')) as SchemaBundle
}

const bundle = loadBundle('music-catalog.schemas.json')
const source = emitSchemas(bundle)

describe('emitSchemas', () => {
  it('emits a do-not-edit header and the schemas const', () => {
    expect(source).toContain('AUTO-GENERATED by @haddowg/json-api-codegen')
    expect(source).toContain('export const schemas = {')
    expect(source).toContain('} as const')
  })

  it('stamps a stable schema hash in the header for drift tracking', () => {
    expect(source).toMatch(/\* Schema hash: [0-9a-f]{16}/)
    // Deterministic: the same bundle always hashes the same (drift-check comparability).
    expect(emitSchemas(bundle)).toBe(source)
  })

  it('has an entry per type, each carrying its resource-object type const', () => {
    const re = /export const schemas = (\{[\s\S]*\}) as const\n$/
    const match = re.exec(source)
    expect(match).not.toBeNull()
    const parsed = JSON.parse(match![1]!) as SchemaBundle

    // oxlint-disable-next-line no-array-sort -- sorting freshly-created key arrays
    expect(Object.keys(parsed).sort()).toEqual(Object.keys(bundle).sort())
    for (const [type, schema] of Object.entries(parsed)) {
      // Each value is the resource-object schema: its `type` property is a const of the key.
      const typeProp = (schema.properties as Record<string, { const?: unknown }> | undefined)?.[
        'type'
      ]
      expect(typeProp?.const).toBe(type)
    }
  })

  it('preserves the raw schema (attributes, $id, dialect) verbatim', () => {
    const re = /export const schemas = (\{[\s\S]*\}) as const\n$/
    const parsed = JSON.parse(re.exec(source)![1]!) as SchemaBundle
    expect(parsed['albums']).toEqual(bundle['albums'])
  })

  it('is deterministic for a given bundle', () => {
    expect(emitSchemas(bundle)).toBe(source)
  })

  it('matches the committed, type-checked snapshot', async () => {
    await expect(source).toMatchFileSnapshot(
      '../test/generated/music-catalog.client.schemas.gen.ts',
    )
  })
})
