import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { buildDescriptor } from './build-descriptor'
import { detectVerbCollisions, emit } from './emit'
import type { ApiDescriptor } from '@haddowg/json-api-client'
import type { OpenApiDocument } from './openapi'

function loadFixture(name: string): OpenApiDocument {
  const path = fileURLToPath(new URL(`../test/fixtures/${name}`, import.meta.url))
  return JSON.parse(readFileSync(path, 'utf8')) as OpenApiDocument
}

const doc = loadFixture('music-catalog.openapi.json')
const descriptor = buildDescriptor(doc)
const source = emit(doc, descriptor)

describe('emit (music-catalog default server)', () => {
  it('writes a do-not-edit header and the runtime import', () => {
    expect(source).toContain('AUTO-GENERATED by @haddowg/json-api-codegen')
    expect(source).toContain("from '@haddowg/json-api-client'")
    expect(source).toContain('createClient as createClientRuntime')
  })

  it('emits an enum union alias only for a referenced enum', () => {
    expect(source).toContain('export type AlbumStatus = "upcoming" | "released" | "withdrawn"')
  })

  it('emits a precise AlbumsAttributes interface', () => {
    expect(source).toContain('export interface AlbumsAttributes {')
    expect(source).toContain('title: string')
    expect(source).toContain('averageRating: number | null')
    expect(source).toContain('artwork: string | null')
    expect(source).toContain('releasedAt: string')
    expect(source).toContain('explicit: boolean')
    expect(source).toContain('status: AlbumStatus')
    expect(source).toContain('availableFrom: string | null')
    // Nested object attribute with its own members (source order preserved), nullable.
    expect(source).toContain('releaseInfo: { label?: string; catalogueNumber?: string } | null')
  })

  it('types an array attribute (tracks.genres)', () => {
    expect(source).toContain('export interface TracksAttributes {')
    expect(source).toContain('genres: unknown[]')
  })

  it('emits an empty interface for an attribute-less type (users)', () => {
    expect(source).toContain('export interface UsersAttributes {}')
  })

  it('emits the resourceMap as const satisfies ApiDescriptor', () => {
    expect(source).toContain('export const resourceMap = {')
    expect(source).toContain('as const satisfies ApiDescriptor')
    expect(source).toContain('export type ResourceMap = typeof resourceMap')
  })

  it('encodes pivot and polymorphic relations in the resourceMap', () => {
    // playlists.orderedTracks is a pivot to-many.
    expect(source).toMatch(/orderedTracks: \{[\s\S]*?pivot: true/)
    // libraries.items is a polymorphic to-many.
    expect(source).toMatch(/items: \{[\s\S]*?types: \[\s*"tracks",\s*"albums",\s*"artists"\s*\]/)
  })

  it('encodes the withCount (Countable) capability in the resourceMap', () => {
    // albums advertises withCount with the `tracks` token + the Countable profile.
    expect(source).toMatch(
      /albums: \{[\s\S]*?countable: \{[\s\S]*?tokens: \[\s*"tracks"\s*\][\s\S]*?profile: "https:\/\/haddowg\.github\.io\/json-api\/profiles\/countable\/"/,
    )
  })

  it('omits `countable` for a type with no withCount endpoint (genres)', () => {
    // Isolate the genres resourceMap entry (lazy up to its closing 2-space-indented brace)
    // so the assertion can't bleed into a later type that does carry `countable`.
    const block = source.match(/\n {2}genres: \{[\s\S]*?\n {2}\}/)?.[0]
    expect(block).toBeDefined()
    expect(block).not.toContain('countable:')
  })

  it('quotes a hyphenated wire-type key', () => {
    expect(source).toContain('"public-profiles": {')
  })

  it('emits an Attributes map from wire type to attribute interface', () => {
    expect(source).toContain('export interface Attributes {')
    expect(source).toContain('albums: AlbumsAttributes')
    expect(source).toContain('"public-profiles": PublicProfilesAttributes')
    expect(source).toContain('tracks: TracksAttributes')
  })

  it('emits a create attribute interface excluding readOnly fields, required from the schema', () => {
    expect(source).toContain('export interface AlbumsCreateAttributes {')
    // readOnly fields (present in the read attributes) are excluded from create.
    expect(source).not.toMatch(/export interface AlbumsCreateAttributes \{[^}]*artwork/)
    expect(source).not.toMatch(/export interface AlbumsCreateAttributes \{[^}]*averageRating/)
    // `title` is required (in the component's `required`); the rest are optional.
    expect(source).toContain('  title: string')
    expect(source).toContain('  explicit?: boolean')
    expect(source).toContain('  status?: AlbumStatus')
  })

  it('emits an update attribute interface with every field optional', () => {
    expect(source).toContain('export interface AlbumsUpdateAttributes {')
    expect(source).toMatch(/export interface AlbumsUpdateAttributes \{[\s\S]*?title\?: string/)
    expect(source).toMatch(/export interface AlbumsUpdateAttributes \{[\s\S]*?explicit\?: boolean/)
    // readOnly fields stay excluded from update too.
    expect(source).not.toMatch(/export interface AlbumsUpdateAttributes \{[^}]*artwork/)
  })

  it('omits write interfaces for a read-only type (no create/update component)', () => {
    expect(source).not.toContain('ChartsCreateAttributes')
    expect(source).not.toContain('ChartsUpdateAttributes')
    expect(source).not.toContain('CountriesCreateAttributes')
    expect(source).not.toContain('UsersCreateAttributes')
  })

  it('emits a WriteAttributes map of per-type create/update pairs, read-only types omitted', () => {
    expect(source).toContain('export interface WriteAttributes {')
    expect(source).toContain(
      'albums: { create: AlbumsCreateAttributes; update: AlbumsUpdateAttributes }',
    )
    expect(source).toContain(
      '"public-profiles": { create: PublicProfilesCreateAttributes; update: PublicProfilesUpdateAttributes }',
    )
    // A read-only type contributes no entry to the map (no `<type>: { create:` line).
    expect(source).not.toMatch(/\n {2}charts: \{ create:/)
    expect(source).not.toMatch(/\n {2}countries: \{ create:/)
    expect(source).not.toMatch(/\n {2}users: \{ create:/)
  })

  it('emits the descriptor-bound createClient factory passing Attributes + WriteAttributes + ActionTypes', () => {
    expect(source).toContain('export const createClient = (options: ClientOptions) =>')
    expect(source).toContain(
      'createClientRuntime<typeof resourceMap, Attributes, WriteAttributes, ActionTypes>(',
    )
    // The server-level atomic capability is threaded into the bound client by default.
    expect(source).toMatch(/createClientRuntime<[^>]*>\([\s\S]*?atomic,\s*\.\.\.options,/)
  })

  it('matches the committed, type-checked snapshot', async () => {
    await expect(source).toMatchFileSnapshot('../test/generated/music-catalog.client.gen.ts')
  })
})

describe('emit (custom actions)', () => {
  it('encodes the actions map in the resourceMap (scope/path/input/output)', () => {
    expect(source).toMatch(/actions: \{[\s\S]*?reissue: \{[\s\S]*?scope: "resource"/)
    expect(source).toMatch(/reissue: \{[\s\S]*?input: "document"[\s\S]*?output: "document"/)
    expect(source).toMatch(/summary: \{[\s\S]*?scope: "collection"[\s\S]*?input: "none"/)
    expect(source).toMatch(/artwork: \{[\s\S]*?input: "raw"/)
  })

  it('emits an Input alias for a document action, nesting the named attribute interface', () => {
    // reissue's input refs AlbumsCreateRequest -> wraps AlbumsCreateAttributes (named, not re-expanded).
    expect(source).toContain('export type AlbumsReissueInput =')
    expect(source).toMatch(/export type AlbumsReissueInput =[\s\S]*?AlbumsCreateAttributes/)
  })

  it('emits an Output alias for a document action, nesting the read attribute interface', () => {
    expect(source).toContain('export type AlbumsReissueOutput =')
    expect(source).toMatch(/export type AlbumsReissueOutput =[\s\S]*?AlbumsAttributes/)
    // summary (no input) gets an Output but no Input alias.
    expect(source).toContain('export type AlbumsSummaryOutput =')
    expect(source).not.toContain('export type AlbumsSummaryInput')
  })

  it('emits no Input alias for a raw-bodied action (artwork)', () => {
    // artwork's body is application/octet-stream — not modelled, so no Input type.
    expect(source).not.toContain('export type AlbumsArtworkInput')
    expect(source).toContain('export type AlbumsArtworkOutput =')
  })

  it('wires the emitted aliases into an ActionTypes map (the client fourth type arg)', () => {
    expect(source).toContain('export interface ActionTypes {')
    // reissue (document in + out) carries both sides; summary (none in) only output.
    expect(source).toMatch(/reissue: \{ input: AlbumsReissueInput; output: AlbumsReissueOutput \}/)
    expect(source).toMatch(/summary: \{ output: AlbumsSummaryOutput \}/)
    // artwork (raw in, document out) carries only its output alias.
    expect(source).toMatch(/artwork: \{ output: AlbumsArtworkOutput \}/)
  })
})

describe('emit (per-relation mutation verbs)', () => {
  it('encodes the verb flags on a to-many relation in the resourceMap', () => {
    expect(source).toMatch(
      /tracks: \{[\s\S]*?mutations: \{[\s\S]*?add: true,[\s\S]*?remove: true,[\s\S]*?replace: true/,
    )
  })

  it('encodes set-only on a to-one relation', () => {
    expect(source).toMatch(/artist: \{[\s\S]*?mutations: \{\s*set: true\s*\}/)
  })
})

describe('emit (atomic capability)', () => {
  it('emits the server-level atomic const for a server with /operations', () => {
    expect(source).toMatch(/export const atomic = \{\s*path: "\/operations"\s*\} as const/)
  })

  it('emits `atomic = null` when the server has no atomic endpoint', () => {
    const noAtomicDoc: OpenApiDocument = {
      components: {
        schemas: {
          WidgetsResource: {
            type: 'object',
            properties: { type: { type: 'string', const: 'widgets' }, id: { type: 'string' } },
          },
        },
      },
      paths: { '/widgets': { get: {} } },
    }
    const noAtomicSource = emit(noAtomicDoc, buildDescriptor(noAtomicDoc))
    expect(noAtomicSource).toContain('export const atomic = null')
  })
})

describe('emit (music-catalog admin server)', () => {
  it('generates cleanly from the admin document', () => {
    const adminDoc = loadFixture('music-catalog-admin.openapi.json')
    const adminSource = emit(adminDoc, buildDescriptor(adminDoc))
    expect(adminSource).toContain('export const resourceMap = {')
    expect(adminSource).toContain('export interface AlbumsAttributes {')
    // The admin server's users type carries real attributes (unlike the default server).
    expect(adminSource).toContain('export interface UsersAttributes {')
    expect(adminSource).toContain('email: string')
    expect(adminSource).toContain('preferences: Record<string, unknown>')
  })
})

describe('emit (descriptions -> JSDoc)', () => {
  it('documents an attribute from its own description', () => {
    expect(source).toContain(
      '  /** Value must be before a dynamically-resolved date/time bound. */\n  releasedAt: string',
    )
  })

  it('documents an attribute whose description rides the $ref wrapper (status)', () => {
    expect(source).toContain(
      '  /** Where the album sits in its release lifecycle. */\n  status: AlbumStatus',
    )
  })

  it('leaves an attribute with no description undocumented', () => {
    // `title` carries no description, so no comment precedes it.
    expect(source).not.toMatch(/\/\*\*[^\n]*\*\/\n  title: string/)
  })

  it('documents enum values as a per-value list above the union alias', () => {
    expect(source).toContain('- `upcoming` — Announced but not yet on sale.')
    expect(source).toContain('- `released` — Released and available to stream or buy.')
    expect(source).toMatch(/\/\*\*\n \* - `upcoming` —[\s\S]*?\*\/\nexport type AlbumStatus =/)
  })
})

describe('detectVerbCollisions', () => {
  it('finds no collisions in the real fixture', () => {
    expect(detectVerbCollisions(descriptor)).toEqual([])
  })

  it('reports a relation named like a reserved verb', () => {
    const synthetic: ApiDescriptor = {
      widgets: {
        attributes: {},
        relations: {
          update: { cardinality: 'one', types: ['gadgets'], pivot: false },
          owner: { cardinality: 'one', types: ['users'], pivot: false },
        },
        paths: {},
        paginator: 'none',
        clientId: 'forbidden',
      },
    }
    expect(detectVerbCollisions(synthetic)).toEqual([{ type: 'widgets', relation: 'update' }])
  })

  it('reports a relation that shadows a runtime handle member (rel/then)', () => {
    const synthetic: ApiDescriptor = {
      widgets: {
        attributes: {},
        relations: {
          rel: { cardinality: 'one', types: ['gadgets'], pivot: false },
          // oxlint-disable-next-line no-thenable -- intentionally probing a `then` relation collision
          then: { cardinality: 'many', types: ['gadgets'], pivot: false },
          owner: { cardinality: 'one', types: ['users'], pivot: false },
        },
        paths: {},
        paginator: 'none',
        clientId: 'forbidden',
      },
    }
    expect(detectVerbCollisions(synthetic)).toEqual([
      { type: 'widgets', relation: 'rel' },
      { type: 'widgets', relation: 'then' },
    ])
  })
})
