import { access, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest'
import { check, generate, schemasOutputPath } from './index'

function fixturePath(name: string): string {
  return fileURLToPath(new URL(`../test/fixtures/${name}`, import.meta.url))
}

const dir = await mkdtemp(join(tmpdir(), 'japi-codegen-'))

// A scratch dir *inside* the package so the generated file's bare
// `@haddowg/json-api-client` import resolves through the workspace when imported.
const localDir = fileURLToPath(new URL('../.codegen-tmp', import.meta.url))

afterAll(async () => {
  await rm(dir, { recursive: true, force: true })
  await rm(localDir, { recursive: true, force: true })
})

describe('generate', () => {
  beforeEach(() => {
    vi.restoreAllMocks()
  })

  it('writes a generated client file into a (created) nested output directory', async () => {
    const output = join(dir, 'nested', 'client.gen.ts')
    const returned = await generate({
      input: fixturePath('music-catalog.openapi.json'),
      output,
    })

    const written = await readFile(output, 'utf8')
    expect(written).toBe(returned)
    expect(written).toContain('AUTO-GENERATED by @haddowg/json-api-codegen')
    expect(written).toContain('export const resourceMap = {')
    expect(written).toContain('export const createClient = (options: ClientOptions) =>')
  })

  it('emits valid, re-parseable TypeScript (strips + imports without throwing)', async () => {
    const output = join(localDir, 'parse', 'client.gen.ts')
    await generate({ input: fixturePath('music-catalog.openapi.json'), output })

    // Node strips TS types on import; a successful dynamic import proves the emitted
    // module is syntactically valid TypeScript and its runtime import resolves.
    const mod = (await import(output)) as { resourceMap: Record<string, unknown> }
    expect(mod.resourceMap['albums']).toBeDefined()
    expect(typeof mod.resourceMap['public-profiles']).toBe('object')
  })

  it('generates from the admin server document without crashing', async () => {
    const output = join(dir, 'admin', 'client.gen.ts')
    await generate({
      input: fixturePath('music-catalog-admin.openapi.json'),
      output,
      server: 'admin',
    })
    const written = await readFile(output, 'utf8')
    expect(written).toContain('albums: {')
    expect(written).toContain('users: {')
  })

  it('does not produce a schema artifact when --schemas is absent', async () => {
    const output = join(dir, 'no-schemas', 'client.gen.ts')
    await generate({ input: fixturePath('music-catalog.openapi.json'), output })

    await expect(access(schemasOutputPath(output))).rejects.toThrow()
    // The main client output is byte-identical to a run with no schemas (unaffected).
    expect(await readFile(output, 'utf8')).toContain('export const resourceMap = {')
  })

  it('writes a per-type schema artifact beside the client when --schemas is set', async () => {
    const output = join(dir, 'schemas', 'client.gen.ts')
    const client = await generate({
      input: fixturePath('music-catalog.openapi.json'),
      output,
      schemas: fixturePath('music-catalog.schemas.json'),
    })

    const schemaPath = schemasOutputPath(output)
    expect(schemaPath).toBe(join(dir, 'schemas', 'client.schemas.gen.ts'))
    const written = await readFile(schemaPath, 'utf8')
    expect(written).toContain('AUTO-GENERATED by @haddowg/json-api-codegen')
    expect(written).toContain('export const schemas = {')

    // The client output is unchanged by the presence of --schemas (separate artifact).
    expect(client).not.toContain('export const schemas =')

    // An entry per type, each value the resource-object schema (has its type const).
    const fixture = JSON.parse(
      await readFile(fixturePath('music-catalog.schemas.json'), 'utf8'),
    ) as Record<string, { properties?: { type?: { const?: unknown } } }>
    const parsed = JSON.parse(
      /export const schemas = (\{[\s\S]*\}) as const\n$/.exec(written)![1]!,
    ) as Record<string, { properties?: { type?: { const?: unknown } } }>
    // oxlint-disable-next-line no-array-sort -- sorting freshly-created key arrays
    expect(Object.keys(parsed).sort()).toEqual(Object.keys(fixture).sort())
    for (const [type, schema] of Object.entries(parsed)) {
      expect(schema.properties?.type?.const).toBe(type)
    }
  })

  it('reads the schema bundle from a URL', async () => {
    const fixture = await readFile(fixturePath('music-catalog.schemas.json'), 'utf8')
    const fetchSpy = vi
      .spyOn(globalThis, 'fetch')
      .mockResolvedValue(new Response(fixture, { status: 200 }))
    try {
      const output = join(dir, 'url-schemas', 'client.gen.ts')
      await generate({
        input: fixturePath('music-catalog.openapi.json'),
        output,
        schemas: 'https://example.test/schemas.json',
      })
      expect(fetchSpy).toHaveBeenCalledWith('https://example.test/schemas.json')
      expect(await readFile(schemasOutputPath(output), 'utf8')).toContain(
        'export const schemas = {',
      )
    } finally {
      fetchSpy.mockRestore()
    }
  })

  it('warns about a relation that collides with a reserved verb', async () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {})
    const input = join(dir, 'collision.openapi.json')
    await import('node:fs/promises').then((fs) =>
      fs.writeFile(input, JSON.stringify(collisionDocument())),
    )

    await generate({ input, output: join(dir, 'collision', 'client.gen.ts') })

    expect(warn).toHaveBeenCalledTimes(1)
    expect(warn.mock.calls[0]![0]).toContain('widgets')
    expect(warn.mock.calls[0]![0]).toContain('update')
  })
})

describe('check (drift gate)', () => {
  it('reports up to date when the committed client matches a fresh generation', async () => {
    const output = join(dir, 'check-ok', 'client.gen.ts')
    await generate({ input: fixturePath('music-catalog.openapi.json'), output })

    const result = await check({ input: fixturePath('music-catalog.openapi.json'), output })
    expect(result.ok).toBe(true)
    expect(result.artifacts).toEqual([{ path: output, upToDate: true }])
  })

  it('does not write anything in check mode', async () => {
    const output = join(dir, 'check-nowrite', 'client.gen.ts')
    // No prior generate: the file does not exist and check must not create it.
    const result = await check({ input: fixturePath('music-catalog.openapi.json'), output })
    expect(result.ok).toBe(false)
    expect(result.artifacts[0]!.upToDate).toBe(false)
    await expect(access(output)).rejects.toThrow()
  })

  it('detects drift when the committed client no longer matches the spec', async () => {
    const output = join(dir, 'check-drift', 'client.gen.ts')
    await generate({ input: fixturePath('music-catalog.openapi.json'), output })
    // Tamper with the committed file to simulate drift.
    await writeFile(output, '// stale\n', 'utf8')

    const result = await check({ input: fixturePath('music-catalog.openapi.json'), output })
    expect(result.ok).toBe(false)
    expect(result.artifacts).toEqual([{ path: output, upToDate: false }])
    // Still no write-back: the tampered content survives (check never repairs).
    expect(await readFile(output, 'utf8')).toBe('// stale\n')
  })

  it('checks the schema artifact too when --schemas is set', async () => {
    const output = join(dir, 'check-schemas', 'client.gen.ts')
    await generate({
      input: fixturePath('music-catalog.openapi.json'),
      output,
      schemas: fixturePath('music-catalog.schemas.json'),
    })

    const result = await check({
      input: fixturePath('music-catalog.openapi.json'),
      output,
      schemas: fixturePath('music-catalog.schemas.json'),
    })
    expect(result.ok).toBe(true)
    expect(result.artifacts.map((a) => a.path)).toEqual([output, schemasOutputPath(output)])

    // Drift in the schema artifact alone is caught.
    await writeFile(schemasOutputPath(output), '// stale\n', 'utf8')
    const drifted = await check({
      input: fixturePath('music-catalog.openapi.json'),
      output,
      schemas: fixturePath('music-catalog.schemas.json'),
    })
    expect(drifted.ok).toBe(false)
    expect(drifted.artifacts).toEqual([
      { path: output, upToDate: true },
      { path: schemasOutputPath(output), upToDate: false },
    ])
  })
})

describe('schemasOutputPath', () => {
  it('derives the schema artifact path from the client output', () => {
    expect(schemasOutputPath('client.gen.ts')).toBe('client.schemas.gen.ts')
    expect(schemasOutputPath('out/dir/api.gen.ts')).toBe('out/dir/api.schemas.gen.ts')
    expect(schemasOutputPath('client.ts')).toBe('client.schemas.ts')
    expect(schemasOutputPath('client')).toBe('client.schemas')
  })
})

/** A tiny synthetic document whose `widgets` type has a relation named `update`. */
function collisionDocument(): unknown {
  return {
    openapi: '3.1.0',
    paths: {},
    components: {
      schemas: {
        WidgetsResource: {
          type: 'object',
          properties: {
            type: { type: 'string', const: 'widgets' },
            relationships: {
              type: 'object',
              properties: {
                update: { $ref: '#/components/schemas/WidgetsUpdateRelationship' },
              },
            },
          },
        },
        WidgetsUpdateRelationship: {
          type: 'object',
          properties: {
            data: {
              anyOf: [{ $ref: '#/components/schemas/GadgetsResourceIdentifier' }, { type: 'null' }],
            },
          },
        },
        GadgetsResourceIdentifier: {
          type: 'object',
          properties: { type: { type: 'string', const: 'gadgets' } },
        },
      },
    },
  }
}
